<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vicky-PC" ignored="0" name="Nop Commerce" tests="9" failures="1" timestamp="2020-06-25T12:12:35 IST" time="235.691" errors="0">
  <testcase name="validateTheLoginPageURL" time="0.16" classname="com.nc.qa.testCases.LoginPageTest"/>
  <testcase name="validateTheLoginPageTitle" time="0.048" classname="com.nc.qa.testCases.LoginPageTest"/>
  <testcase name="validateTheLoginFunctionality" time="11.983" classname="com.nc.qa.testCases.LoginPageTest"/>
  <testcase name="verifyAddNewCustomerPageURL" time="0.032" classname="com.nc.qa.testCases.CreateCustomerPageTest"/>
  <testcase name="verifyAddNewCustomerPageTitle" time="0.029" classname="com.nc.qa.testCases.CreateCustomerPageTest"/>
  <testcase name="verifyAddNewCustomer" time="7.223" classname="com.nc.qa.testCases.CreateCustomerPageTest"/>
  <testcase name="verifyEditCustomerPageTitleTest" time="0.176" classname="com.nc.qa.testCases.EditCustomerPageTest"/>
  <testcase name="editCustomerDetailsTest" time="5.232" classname="com.nc.qa.testCases.EditCustomerPageTest"/>
  <testcase name="deleteCustomerDetails" time="4.203" classname="com.nc.qa.testCases.DeleteCustomerPageTest">
    <failure type="java.lang.AssertionError" message="expected [×
The customer has been deleted successfully.] but found [×
The customer has been deleted successfully.]">
      <![CDATA[java.lang.AssertionError: expected [×
The customer has been deleted successfully.] but found [×
The customer has been deleted successfully.]
at com.nc.qa.testCases.DeleteCustomerPageTest.deleteCustomerDetails(DeleteCustomerPageTest.java:56)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomerDetails -->
</testsuite> <!-- Nop Commerce -->
